-- AlterEnum
ALTER TYPE "NotificationType" ADD VALUE 'LOAN_APPLICATION_RECEIVED';
ALTER TYPE "NotificationType" ADD VALUE 'LOAN_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE 'LOAN_CANCELLED';
ALTER TYPE "NotificationType" ADD VALUE 'COLLATERAL_ADDED';
ALTER TYPE "NotificationType" ADD VALUE 'REPAYMENT_OVERDUE';
